# Generated by Django 3.1.7 on 2021-03-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210315_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Genres'},
        ),
    ]
